from __future__ import annotations

import re

from .common import bbox_of, eligible_text_units, reading_order, role_of, text_of


PAGE_NUMBER_RE = re.compile(r"^\s*(?:\d+|[ivxlcdm]+)\s*$", re.IGNORECASE)
# Publisher / scan artefacts. Tolerant to hyphens and accents:
# "Estadísticos e-Books & Papers", "e-books & papers", "Downloaded from", etc.
PUBLISHER_RE = re.compile(
    r"(?:e-?books?\s*&\s*papers|estad[ií]sticos|\bebook\b|\bpublisher\b|\bmanning\b"
    r"|\bcopyright\b|©|all rights reserved|downloaded from|generated by|scanned by|pdfdrive)",
    re.IGNORECASE,
)
WATERMARK_RE = re.compile(r"\b(?:watermark|draft|sample|preview|confidential)\b", re.IGNORECASE)


def build_artifacts(units: list[dict], *, page_intelligence: dict | None = None) -> dict:
    page_intelligence = page_intelligence or {}
    by_id = {u.get("unit_id"): u for u in units if isinstance(u, dict) and u.get("unit_id")}
    publisher_marks: list[dict] = []
    watermarks: list[dict] = []
    page_numbers: list[dict] = []
    for idx, unit in enumerate(eligible_text_units(units), start=1):
        # Prefer line/block level artifacts. Phrase/span copies of the same page
        # number/header artifact cause duplicate overlays in reconstruction.
        if unit.get("level") in {"phrase", "span", "word", "char"} and _has_artifact_parent(unit, by_id):
            continue
        role = role_of(unit)
        text = text_of(unit)
        bbox = bbox_of(unit)
        location = _vertical_location(bbox, page_intelligence)
        if role == "publisher_mark" or PUBLISHER_RE.search(text):
            publisher_marks.append(_artifact("publisher_mark", idx, unit, "exclude_as_artifact", location))
        elif role == "watermark" or WATERMARK_RE.search(text):
            watermarks.append(_artifact("watermark", idx, unit, "exclude_as_artifact", location))
        elif role in {"page_reference", "page_number", "toc_page_reference"} or (
            unit.get("level") in {"block", "line", "phrase"}
            and PAGE_NUMBER_RE.fullmatch(text)
            and location in {"top_margin", "bottom_margin"}
        ):
            page_numbers.append(_artifact("page_number", idx, unit, "preserve_text_exactly", location))
    return {
        "publisher_marks": _dedupe_artifacts(publisher_marks),
        "watermarks": _dedupe_artifacts(watermarks),
        "page_numbers": _dedupe_artifacts(page_numbers),
    }


def _has_artifact_parent(unit: dict, by_id: dict[str, dict]) -> bool:
    cursor = unit
    while cursor.get("parent_id") in by_id:
        parent = by_id[cursor.get("parent_id")]
        role = role_of(parent)
        text = text_of(parent)
        if role in {"publisher_mark", "watermark", "page_reference", "page_number", "toc_page_reference"}:
            return True
        if PUBLISHER_RE.search(text) or WATERMARK_RE.search(text) or PAGE_NUMBER_RE.fullmatch(text):
            return True
        cursor = parent
    return False


def _dedupe_artifacts(items: list[dict]) -> list[dict]:
    output: list[dict] = []
    for item in items:
        text = re.sub(r"\s+", " ", str(item.get("text") or "").strip()).lower()
        bbox = item.get("bbox") or []
        duplicate = False
        for kept in output:
            kept_text = re.sub(r"\s+", " ", str(kept.get("text") or "").strip()).lower()
            if text == kept_text and _bbox_overlap_ratio(bbox, kept.get("bbox") or []) >= 0.7:
                duplicate = True
                break
        if not duplicate:
            output.append(item)
    return output


def _bbox_overlap_ratio(a, b) -> float:
    if not isinstance(a, (list, tuple)) or not isinstance(b, (list, tuple)) or len(a) != 4 or len(b) != 4:
        return 0.0
    ax0, ay0, ax1, ay1 = [float(v) for v in a]
    bx0, by0, bx1, by1 = [float(v) for v in b]
    ix0, iy0 = max(ax0, bx0), max(ay0, by0)
    ix1, iy1 = min(ax1, bx1), min(ay1, by1)
    inter = max(0.0, ix1 - ix0) * max(0.0, iy1 - iy0)
    area = max(1.0, min(max(0.0, ax1 - ax0) * max(0.0, ay1 - ay0), max(0.0, bx1 - bx0) * max(0.0, by1 - by0)))
    return inter / area


def _artifact(kind: str, idx: int, unit: dict, preservation_mode: str, location: str) -> dict:
    return {
        "logical_unit_id": f"{kind}_{idx:04d}",
        "type": kind,
        "text": text_of(unit),
        "source_unit_ids": [unit["unit_id"]],
        "bbox": bbox_of(unit),
        "role": kind,
        "preservation_mode": preservation_mode,
        "location": location,
        "reading_order_index": reading_order(unit),
    }


def _vertical_location(bbox, page_intelligence: dict) -> str:
    if not isinstance(bbox, (list, tuple)) or len(bbox) != 4:
        return "unknown"
    page_geometry = page_intelligence.get("page_geometry") or {}
    height = float(page_geometry.get("height") or 0.0)
    dpi = float(page_geometry.get("render_dpi") or 72.0)
    if height and dpi:
        height = height * 72.0 / dpi
    if not height:
        return "unknown"
    y0 = float(bbox[1])
    y1 = float(bbox[3])
    if y1 < height * 0.12:
        return "top_margin"
    if y0 > height * 0.88:
        return "bottom_margin"
    return "body_area"
