name: docs_parser_demo_studio
description: Application desktop locale pour piloter le pipeline docs_parser.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
